name: Deploy Docker image

env:
  docker_image_name: kevcoder/stripe-proxy-node
  version_major: 2
  version_minor: 0
  version_patch: $(date +%s)

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
     
      - name: Build and Deploy the Docker Image
        env:
          DOCKER_REGISTRY: registry.digitalocean.com
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_REGISTRY }}/${{ env.docker_image_name }}:${{ env.version_major }}.${{ env.version_minor }}.${{ env.version_patch }} --tag ${{ env.DOCKER_REGISTRY }}/${{ env.docker_image_name }}:latest
          echo ${{ secrets.DO_CONTAINER_REGISTRY_PWD }} | docker login ${{ env.DOCKER_REGISTRY }} --username ${{ secrets.DO_CONTAINER_REGISTRY_USER_NAME }} --password-stdin
          docker push --all-tags ${{ env.DOCKER_REGISTRY }}/${{ env.docker_image_name }}
          docker logout ${{ env.DOCKER_REGISTRY }}
      
      