name: Deploy Docker image

env:
  docker_image_name: kevcoder/stripe-proxy
  version_major: 2
  version_minor: 0
  version_patch: $(date +%s)

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo $docker_image_name, $version_major, $version_minor, $version_patch
      - run: docker build . --file Dockerfile --tag ${{ env.docker_image_name }}:${{ env.version_major }}.${{ env.version_minor }}.${{ env.version_patch }} --tag ${{ env.docker_image_name }}:latest
      
      